### ISSUE TITLE
Docker Image fails to build

### ISSUE THREAD

**Issue by deric4** [simonkeng/rdkit-jupyter-docker#3]
#### rdkit-jupyter-docker release or commit:
255cac9e2c80eefaca9897c0eba87f076b0a0342

#### Operating System/Architecture:
macOS 10.13.4

#### docker version
```
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
```

#### Logs
<details>
    <summary><b>Click to view Log Output</b></summary>

```
$ docker-compose up --build

Attaching to rdkit-jupyter-docker_notebook_1
notebook_1  | [I 02:50:33.904 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
notebook_1  | Traceback (most recent call last):
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
notebook_1  |     value = obj._trait_values[self.name]
notebook_1  | KeyError: 'allow_remote_access'
notebook_1  |
notebook_1  | During handling of the above exception, another exception occurred:
notebook_1  |
notebook_1  | Traceback (most recent call last):
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
notebook_1  |     addr = ipaddress.ip_address(self.ip)
notebook_1  |   File "/opt/conda/lib/python3.6/ipaddress.py", line 54, in ip_address
notebook_1  |     address)
notebook_1  | ValueError: '' does not appear to be an IPv4 or IPv6 address
notebook_1  |
notebook_1  | During handling of the above exception, another exception occurred:
notebook_1  |
notebook_1  | Traceback (most recent call last):
notebook_1  |   File "/opt/conda/bin/jupyter-notebook", line 11, in <module>
notebook_1  |     sys.exit(main())
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
notebook_1  |     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
notebook_1  |     app.initialize(argv)
notebook_1  |   File "<decorator-gen-7>", line 2, in initialize
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
notebook_1  |     return method(app, *args, **kwargs)
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1629, in initialize
notebook_1  |     self.init_webapp()
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1379, in init_webapp
notebook_1  |     self.jinja_environment_options,
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 158, in __init__
notebook_1  |     default_url, settings_overrides, jinja_env_options)
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 251, in init_settings
notebook_1  |     allow_remote_access=jupyter_app.allow_remote_access,
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
notebook_1  |     return self.get(obj, cls)
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
notebook_1  |     value = self._validate(obj, dynamic_default())
notebook_1  |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
notebook_1  |     for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
notebook_1  |   File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
notebook_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
notebook_1  | socket.gaierror: [Errno -2] Name or service not known
rdkit-jupyter-docker_notebook_1 exited with code 1
```
</details>

#### Expected Behavior:

Container should have output connection instructions and start notebook server

**Actual Behavior:**

Container failed to start cleanly

**Steps to Reproduce:**

1. Force a new image build and start container
    ```bash
    docker-compose up --build
    ```

**Comment by simonkeng** [comment]
Thanks for identifying this @Deric4.
